name = Uks
description = Unknown Soldier layout
template = uks-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/uks/uks.layout.css
stylesheets[all][] = css/layouts/uks/uks.layout.no-query.css