name = Concepts
description = Concepts page layout
template = concepts-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/concepts/concepts.layout.css
stylesheets[all][] = css/layouts/concepts/concepts.layout.no-query.css