name = coreSample
description = Core Sample layout
template = coreSample-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/coreSample/coreSample.layout.css
stylesheets[all][] = css/layouts/coreSample/coreSample.layout.no-query.css